### ISSUE TITLE
Dark mode doesn't work on webkit.

### ISSUE THREAD

**Issue by Lcarv20** [MAHcodes/gleez#1]
This is highly likely to be a missing tailwind  property that is not necessary on other browsers.
<img width="1436" alt="Screenshot 2024-05-06 at 15 47 29" src="https://github.com/MAHcodes/gleez/assets/42584819/1922974c-3898-4d5c-8bc4-67a519f211ee">

**Comment by Lcarv20** [comment]
After a brief inspection I found that the bug is related on how the hsl value of the background is declared. Hsl values are composed by three numbers. the 2nd and 3rd number are % values. Chromium and gecko browsers are tolerant to the missing % symbol on the declaration, but not webkit. Webkit will not convert 0 to 0%.

My suggestion is to change the following lines:

```diff
-     --background: 0 0 7%;
+     --background: 0 0% 7%;
```

**Comment by Lcarv20** [comment]
Closed by mistake. wait until #2 is merged

**Comment by MAHcodes** [comment]
Awesome, Thank you!
